---
    # Example: ansible-playbook -i hosts/azure/dev/ inventory_count.yml
    
    - name: Show the total count of hosts in the dynamic inventory
      hosts: all
      gather_facts: false
      connection: local
    
      tasks:
      - debug:
          msg: "Total hosts: {{ groups['all'] | length }}"
        run_once: true
    